name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      
      - name: Login on Docker hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./src
          file: ./docker/Dockerfile
          push: true
          tags: |
            c410l/kube-news:v${{ github.run_number }}
            c410l/kube-news:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3.5.3
      
      - name: Autenticar o AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Configuração do Kubectl
        shell: bash
        run: |
          aws eks update-kubeconfig --name eks-kubenews --region us-east-1

      - name: Deploy das aplicações
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: k8s/
          images: c410l/kube-news:v${{ github.run_number }}
